# Generated by Django 4.1 on 2022-08-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiares',
            new_name='Familia',
        ),
    ]
