# Generated by Django 4.1 on 2022-08-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0003_familiares_delete_familia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiares',
            old_name='edad',
            new_name='Edad',
        ),
        migrations.RenameField(
            model_name='familiares',
            old_name='fecha_nacimiento',
            new_name='Fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='familiares',
            old_name='nombre',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='familiares',
            old_name='parentesco',
            new_name='Parentesco',
        ),
    ]
