# Generated by Django 4.1 on 2022-09-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFamiliares', '0004_rename_edad_familiares_edad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiares',
            old_name='Edad',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='familiares',
            old_name='Fecha_nacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='familiares',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='familiares',
            old_name='Parentesco',
            new_name='parentesco',
        ),
    ]
